### ISSUE TITLE
Language MissMatch

### ISSUE THREAD

**Issue by CryogenicPlanet** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#24]
https://twitter.com/BathtubPhysici1/status/1258474392004096001?s=19

@rithvikmahin Can you check this in the nlp processing or does it have to be a different checker?

**Comment by CryogenicPlanet** [comment]
![image](https://user-images.githubusercontent.com/10355479/81400289-623d1880-914a-11ea-9299-3993bb8d4abb.png)

Article body is in french

**Comment by CryogenicPlanet** [comment]
https://twitter.com/whosaidthis_bot/status/1258765852343754752?s=19

![image](https://user-images.githubusercontent.com/10355479/81415948-b5bd5f80-9166-11ea-987e-020722a816ab.png)

**Comment by rithvikmahin** [comment]
Cause of issue: The sources found include PDF documents and academic papers that are very long, with over 1.5 million characters. SpaCy takes too long (over 30 seconds) to run nlp(text) and create a document object from the text and stalls the entire processing system. 

Temporary solution: Created a timer that stops processing that document if it takes longer than 30 seconds and moves on to the next one.

Potential solution / TODO: Add a queue for all tweets that take longer than 30 seconds to process, and return a "Will provide the source later" statement to the user. Once the tweets are processed, return them to the user at any point in time later.

**Comment by rithvikmahin** [comment]
Improved NLP with weights.
