### ISSUE TITLE
Bad NLP of Tweet

### ISSUE THREAD

**Issue by CryogenicPlanet** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#32]
https://twitter.com/gaurang_bharti/status/1259239353189986304

**Score Result : 1.2801521507188693** 

![image](https://user-images.githubusercontent.com/10355479/81485672-97da2280-926c-11ea-977b-1a63973a2b29.png)

**Final Source https://www.phe.gov/Preparedness/planning/abc/Pages/tribal-preparedness.aspx**

**Comment by rithvikmahin** [comment]
Text File:
[output.txt](https://github.com/Mozilla-Open-Lab-Etwas/Twitter-Source-Bot/files/4604573/output.txt)

**Comment by rithvikmahin** [comment]
Fixed Source: https://www.bia.gov/as-ia/opa/online-press-release/cares-act-provides-critical-assistance-tribal-governments

Added a weighted emphasis to proper nouns to improve the odds of capturing important words.
