### ISSUE TITLE
Tweet response was ASCII jibberish and 1964 empty items

### ISSUE THREAD

**Issue by gaurangbharti1** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#34]
Tweet: https://twitter.com/People_Of_Space/status/1246926720160141312

1964 empty items

![image](https://user-images.githubusercontent.com/23725257/81487599-52255600-927c-11ea-9760-edfcc9141a2d.png)

**Comment by CryogenicPlanet** [comment]
Error in NLP.js fixed with updating code
