### ISSUE TITLE
Handle retweets of the bot

### ISSUE THREAD

**Issue by gaurangbharti1** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#35]
https://twitter.com/whosaidthis_bot/status/1259271209822363648

If the bot's response is retweeted, handle it accordingly.

**Comment by gaurangbharti1** [comment]
![image](https://user-images.githubusercontent.com/23725257/81487874-8ea68100-927f-11ea-882f-3915d22bb45c.png)

**Comment by CryogenicPlanet** [comment]
Associate Error  with #8 and #23
