### ISSUE TITLE
Puppeteer Title Retrive Bug

### ISSUE THREAD

**Issue by CryogenicPlanet** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#55]
https://twitter.com/salegot1/status/1259950986988150784

![image](https://user-images.githubusercontent.com/10355479/81611423-a48b8180-93f8-11ea-9031-97155c32f66e.png)

The article is perfect but puppeteer didn't retrieve a proper title

**Comment by BK-Modding** [comment]
Bypassed it using puppeteer-extra, puppeteer-extra-plugin-stealth, and puppeteer-extra-plugin-recaptcha.
