### ISSUE TITLE
Bad source

### ISSUE THREAD

**Issue by BK-Modding** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#65]
![image](https://user-images.githubusercontent.com/14833123/81878081-911d1980-95a4-11ea-8ac3-f541446e30fa.png)

tweet: https://twitter.com/whosaidthis_bot/status/1260718805950627840

output file: http://34.71.148.202:3000/nlpOutput?tweetId=1259952106049421300

**Comment by rithvikmahin** [comment]
Resolved. Added priority for verbs.
