### ISSUE TITLE
Bad Source on Example Tweet

### ISSUE THREAD

**Issue by CryogenicPlanet** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#68]
https://twitter.com/zzzzhe/status/1260439146411286531

![image](https://user-images.githubusercontent.com/10355479/81879394-4a312300-95a8-11ea-9fdd-88fd10b8dc94.png)

**Before Mongo so not output log**

**Comment by rithvikmahin** [comment]
Resolved.
