### ISSUE TITLE
Fix datetime comparison for caching check

### ISSUE THREAD

**Issue by BK-Modding** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#69]
Line permalink: https://github.com/Mozilla-Open-Lab-Etwas/Twitter-Source-Bot/blob/43ae9e9333e9d5a49efc9f55aebb1c502a00de4f/modules/tweet.js#L159

**Comment by CryogenicPlanet** [comment]
@lunaroyster Any ideas why this did not work? Like this if statement didn't work

**Comment by BK-Modding** [comment]
Was a comparison operator mistake. Used "<" instead of ">"
