### ISSUE TITLE
Update to Puppeteer caused bad nlp

### ISSUE THREAD

**Issue by CryogenicPlanet** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#71]
https://twitter.com/whosaidthis_bot/status/1261061520991170560

![image](https://user-images.githubusercontent.com/10355479/81992444-12d27d00-9661-11ea-97da-0fa201df744c.png)

NLP Output: http://34.71.148.202:3000/nlpOutput?tweetId=1259940980142243841

@rithvikmahin Something weird was happening I don't know how that previous page was getting cited but anyways by making puppeteer more stealh that pages finishes later cause it doesn't instantly respond and it causes this bad nlp.

**Comment by CryogenicPlanet** [comment]
https://github.com/Mozilla-Open-Lab-Etwas/Twitter-Source-Bot/blob/dev/dataTemplates/accessDenied.png

**Comment by rithvikmahin** [comment]
Fixed by updating the overall threshold to 0.45, and tweaking the whitelist threshold increase to 0.1.
