### ISSUE TITLE
Python can't handle too many requests

### ISSUE THREAD

**Issue by gaurangbharti1** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#77]
![image](https://user-images.githubusercontent.com/23725257/82109890-658e6080-9757-11ea-889e-80ac1c85cdaf.png)

**Comment by CryogenicPlanet** [comment]
#78 Temporary solution, but this needs to be fixed immediately along with #64

**Comment by CryogenicPlanet** [comment]
#94 Added Secondary Backup Scraper in Promise Race, bringing it up to three scrapers
