### ISSUE TITLE
NLP broken

### ISSUE THREAD

**Issue by gaurangbharti1** [Mozilla-Open-Lab-Etwas/Twitter-Source-Bot#80]
![image](https://user-images.githubusercontent.com/23725257/82135955-03506100-9826-11ea-8608-74d0ef1234a2.png)
https://twitter.com/BarackObama/status/1261823767044476928

**Comment by CryogenicPlanet** [comment]
The sources were good cause google did the heavy lifting of the reverse video but the word obama was not a keyword so @rithvikmahin do you want to add the tweeter's name into the keywords at least for nlp

**Comment by CryogenicPlanet** [comment]
Resolved by adding user's name as NNP in the keywords list

https://twitter.com/salegot1/status/1261923238143123457

http://34.71.148.202:3000/nlpOutput?tweetId=1261823767044476928
